INSERT INTO categories (name, slug, color, description) VALUES
('Nasional', 'nasional', '#1D4ED8', 'Berita utama isu nasional dan pemerintahan Indonesia.'),
('Politik', 'politik', '#B91C1C', 'Kabar politik, parlemen, dan pemilu.'),
('Bisnis', 'bisnis', '#2563EB', 'Berita ekonomi, keuangan, bursa efek, dan bisnis.'),
('Teknologi', 'teknologi', '#DC2626', 'Berita teknologi, AI, digitalisasi, dan startup.'),
('Lifestyle', 'lifestyle', '#DB2777', 'Gaya hidup, kesehatan, dan tren masyarakat.'),
('Entertainment', 'entertainment', '#9333EA', 'Dunia hiburan, seni, dan perfilman.'),
('Sports', 'sports', '#059669', 'Berita olahraga nasional dan internasional.'),
('Daerah', 'daerah', '#D97706', 'Kabar regional dan dinamika kabupaten/kota.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO authors (name, slug, bio, role) VALUES
('Ahmad Rizky Pratama', 'ahmad-rizky-pratama', 'Senior journalist liputan bisnis nasional.', 'Chief Editor'),
('Siti Nurhaliza', 'siti-nurhaliza', 'Reporter pendidikan & isu nasional.', 'Senior Reporter'),
('Budi Santoso', 'budi-santoso', 'Jurnalis budaya dan gaya hidup.', 'Culture Editor'),
('Reza Firmansyah', 'reza-firmansyah', 'Jurnalis olahraga nasional.', 'Sports Reporter')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO articles (title, slug, subtitle, excerpt, content, thumbnail, status, published_at, category_id, author_id, view_count, reading_time, featured, breaking, seo_title, seo_description, canonical_url) VALUES
('Pemerintah Resmikan Peta Jalan Pertumbuhan Ekonomi 8 Persen 2026-2030', 'pemerintah-resmikan-peta-jalan-pertumbuhan-ekonomi-8-persen', 'Fokus utama pada hilirisasi industri, energi hijau, dan digitalisasi UMKM.', 'Pemerintah meluncurkan target pertumbuhan ekonomi nasional sebesar 8 persen yang didukung efisiensi birokrasi dan investasi strategis.', '<p>Pemerintah Indonesia secara resmi menetapkan Peta Jalan Pertumbuhan Ekonomi Nasional 8 Persen periode 2026-2030.</p><p>Target ini optimis dicapai melalui penguatan hilirisasi komoditas unggulan dan percepatan adopsi kecerdasan buatan di sektor manufaktur.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='nasional' LIMIT 1), (SELECT id FROM authors WHERE slug='ahmad-rizky-pratama' LIMIT 1), 24500, 5, true, true, 'Pemerintah Resmikan Peta Jalan Ekonomi 8 Persen', 'Target pertumbuhan ekonomi 8 persen diluncurkan.', 'https://metrikmediaindonesia.id/news/pemerintah-resmikan-peta-jalan-pertumbuhan-ekonomi-8-persen'),
('Dinamika Koalisi Parlemen dan Pembahasan RUU Pemilu 2029 Mulai Bergulir', 'dinamika-koalisi-parlemen-dan-pembahasan-ruu-pemilu-2029', 'Fraksi-fraksi di DPR mulai menyepakati poin krusial ambang batas parlemen.', 'Pembahasan RUU Pemilu 2029 resmi dimulai di Senayan dengan fokus penyempurnaan sistem pemungutan suara elektronik.', '<p>Komisi II DPR RI menggelar rapat dengar pendapat umum bersama para pakar hukum tata negara terkait revisi Undang-Undang Pemilihan Umum.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='politik' LIMIT 1), (SELECT id FROM authors WHERE slug='siti-nurhaliza' LIMIT 1), 18900, 5, true, false, 'Pembahasan RUU Pemilu 2029 Dimulai', 'DPR bahas RUU Pemilu 2029.', 'https://metrikmediaindonesia.id/news/dinamika-koalisi-parlemen-dan-pembahasan-ruu-pemilu-2029'),
('Pasar Saham Indonesia Catat Rekor Tertinggi Sepanjang Sejarah Tembus 8.000', 'pasar-saham-indonesia-catat-rekor-tertinggi-sepanjang-sejarah', 'IHSG bergerak menguat didorong aksi beli bersih investor asing.', 'Indeks Harga Saham Gabungan (IHSG) menembus level psikologis 8.000 didorong optimisme pertumbuhan ekonomi domestik.', '<p>Bursa Efek Indonesia mengukir sejarah baru setelah IHSG ditutup menguat signifikan di level 8.025.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='bisnis' LIMIT 1), (SELECT id FROM authors WHERE slug='ahmad-rizky-pratama' LIMIT 1), 31200, 5, true, true, 'Pasar Saham Catat Rekor Tertinggi', 'IHSG tembus level 8.000.', 'https://metrikmediaindonesia.id/news/pasar-saham-indonesia-catat-rekor-tertinggi-sepanjang-sejarah'),
('Kedaulatan Data dan Kebijakan Pengembangan Artificial Intelligence Indonesia', 'kedaulatan-data-dan-kebijakan-pengembangan-ai-indonesia', 'Pemerintah merilis standar etika dan keamanan data nasional untuk adopsi AI.', 'Pedoman nasional penggunaan AI dirilis guna memastikan perlindungan data pribadi konsumen dan etika algoritma.', '<p>Pemerintah Indonesia menerbitkan pedoman etika penggunaan kecerdasan buatan bagi industri dan lembaga pemerintah.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='teknologi' LIMIT 1), (SELECT id FROM authors WHERE slug='ahmad-rizky-pratama' LIMIT 1), 19800, 5, false, false, 'Kedaulatan Data & AI Indonesia', 'Pedoman etika AI dirilis.', 'https://metrikmediaindonesia.id/news/kedaulatan-data-dan-kebijakan-pengembangan-ai-indonesia'),
('Tren Gaya Hidup Sehat Urban: Kesadaran Nutrisi Organik dan Olahraga Teratur', 'tren-gaya-hidup-sehat-urban-kesadaran-nutrisi-organik', 'Masyarakat perkotaan kian aktif mengadopsi pola makan seimbang.', 'Kesadaran akan kesehatan mental dan fisik mendorong gaya hidup berbasis pangan lokal organik dan olahraga komunitas.', '<p>Gaya hidup sehat menjadi prioritas utama generasi muda perkotaan di Indonesia.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='lifestyle' LIMIT 1), (SELECT id FROM authors WHERE slug='budi-santoso' LIMIT 1), 14200, 5, false, false, 'Tren Gaya Hidup Sehat Urban', 'Kesadaran nutrisi organik urban.', 'https://metrikmediaindonesia.id/news/tren-gaya-hidup-sehat-urban-kesadaran-nutrisi-organik'),
('Film Karya Sutradara Muda Indonesia Berhasil Tembus Festival Film Cannes', 'film-karya-sutradara-muda-indonesia-berhasil-tembus-cannes', 'Apresiasi tinggi dari kritikus film internasional untuk perfilman tanah air.', 'Karya sineas muda tanah air berkompetisi di kategori utama Festival Film Internasional Cannes.', '<p>Dunia perfilman Indonesia kembali bangga setelah karya sutradara berbakat berhasil masuk jajaran kompetisi utama Festival Film Cannes.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='entertainment' LIMIT 1), (SELECT id FROM authors WHERE slug='budi-santoso' LIMIT 1), 22100, 5, false, false, 'Film Indonesia Tembus Festival Cannes', 'Sineas muda masuk Festival Cannes.', 'https://metrikmediaindonesia.id/news/film-karya-sutradara-muda-indonesia-berhasil-tembus-cannes'),
('Timnas Garuda Muda Tampil Gemilang di Kualifikasi Piala Dunia U-20', 'timnas-garuda-muda-tampil-gemilang-di-kualifikasi-piala-dunia-u-20', 'Kemenangan dramatis 2-1 menegaskan kesiapan tim nasional di kancah dunia.', 'Garuda Muda mengamankan tiket fase gugur setelah menaklukkan tim kuat dalam laga ketat di Stadion GBK.', '<p>Tim Nasional Indonesia U-20 sukses melaju ke babak selanjutnya setelah menumbangkan tim lawan 2-1.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='sports' LIMIT 1), (SELECT id FROM authors WHERE slug='reza-firmansyah' LIMIT 1), 34000, 5, true, true, 'Garuda Muda Gemilang Kualifikasi Pildun U-20', 'Garuda U-20 kalahkan tim lawan 2-1.', 'https://metrikmediaindonesia.id/news/timnas-garuda-muda-tampil-gemilang-di-kualifikasi-piala-dunia-u-20'),
('Pemerintah Daerah Jawa Barat Luncurkan Pusat Inovasi Pelayanan Publik Digital', 'pemerintah-daerah-jawa-barat-luncurkan-pusat-inovasi-pelayanan-publik', 'Layanan perizinan dan administrasi warga kini dapat diakses dalam satu aplikasi terpadu.', 'Inovasi sistem digitalisasi Pemprov Jabar memangkas waktu pengurusan izin usaha menjadi hanya beberapa menit.', '<p>Pemerintah Provinsi Jawa Barat meresmikan Pusat Inovasi Pelayanan Publik Digital di Bandung.</p>', '/image-placeholder.svg', 'published', NOW(), (SELECT id FROM categories WHERE slug='daerah' LIMIT 1), (SELECT id FROM authors WHERE slug='siti-nurhaliza' LIMIT 1), 16700, 5, false, false, 'Pemda Jabar Luncurkan Pelayanan Digital', 'Pusat Inovasi Pelayanan Publik Jabar.', 'https://metrikmediaindonesia.id/news/pemerintah-daerah-jawa-barat-luncurkan-pusat-inovasi-pelayanan-publik')
ON CONFLICT (slug) DO NOTHING;
